disabled_rules:
  - function_body_length
  - cyclomatic_complexity
  - file_length
  - line_length
  - type_body_length
  - force_cast
  - unused_optional_binding
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Modules
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 
  warning: 110
type_name:
  max_length: 60
# they can set both implicitly with an array
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
